import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Cursor from "@/components/Cursor/Cursor";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   // preload: [
//   //   { rel: 'preload', as: 'image', href: '/portada.jpg' }
//   // ]
// }

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>     
        <Cursor />
        <Header />
        {children}
      </body>
    </html>
  );
}
